version: '3.8'

services:
  frontend:
    networks:
      - internal-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_API_KEY: ${VITE_API_KEY}
    volumes:
      -  ./src:/app/src
    restart:
      unless-stopped

networks:
  internal-network:
    name: internal-network
    driver: bridge
